### ISSUE TITLE
Java heap space when trying to copy a big code snipped

### ISSUE THREAD

**Issue by mcprol** [mcprol/pmd-apex-kiuwan-plugin#1]
INFO 2019-05-13 22:47:19,836 - com.als.core.OptimythException: Java heap space
INFO 2019-05-13 22:47:19,850 -  at com.als.core.main.AbstractStaticAnalyzer.analyze(AbstractStaticAnalyzer.java:167)
INFO 2019-05-13 22:47:19,862 -  at com.als.core.main.Main.run(Main.java:200)
INFO 2019-05-13 22:47:19,863 -  at com.als.core.main.Main.run(Main.java:126)
INFO 2019-05-13 22:47:19,863 -  at com.als.core.main.Main.main(Main.java:85)
INFO 2019-05-13 22:47:19,863 - Caused by: java.lang.OutOfMemoryError: Java heap space
INFO 2019-05-13 22:47:19,863 -  at java.util.Arrays.copyOf(Arrays.java:3332)
INFO 2019-05-13 22:47:19,865 -  at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
INFO 2019-05-13 22:47:19,865 -  at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
INFO 2019-05-13 22:47:19,865 -  at java.lang.StringBuilder.append(StringBuilder.java:136)
INFO 2019-05-13 22:47:19,866 -  at java.lang.StringBuilder.append(StringBuilder.java:76)
INFO 2019-05-13 22:47:19,866 -  at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:484)
INFO 2019-05-13 22:47:19,866 -  at java.lang.StringBuilder.append(StringBuilder.java:166)
INFO 2019-05-13 22:47:19,867 -  at java.util.StringJoiner.add(StringJoiner.java:185)
INFO 2019-05-13 22:47:19,867 -  at java.lang.String.join(String.java:2456)
INFO 2019-05-13 22:47:19,867 -  at mcp.kiuwan.rules.pmd.apex.PmdApexKiuwanPlugin$PmdApexReportHandler.getCodeFragment(PmdApexKiuwanPlugin.java:235)
INFO 2019-05-13 22:47:19,867 -  at mcp.kiuwan.rules.pmd.apex.PmdApexKiuwanPlugin$PmdApexReportHandler.characters(PmdApexKiuwanPlugin.java:212)

**Comment by mcprol** [comment]
Now, only a code fragment (5 lines maximum) is copied to kiuwan defect/vulnerability
